config/routes.rb
TestApp::Application.routes.draw do

  get "slams/create"

  post "slams/new"

  get "slams/index"

  get "slams/show"

  
  root to: 'static_pages#home'
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/news', to: 'static_pages#news'
  match '/maps', to: 'users#maps'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base

	 

	  attr_accessible :name, :email, :password, :password_confirmation, :location, :latitude, :longitude
	  has_secure_password

	  # microposts
	  has_many :microposts, dependent: :destroy

	  # for followers
	  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  	  has_many :followed_users, through: :relationships

  	  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
 	  has_many :followers, through: :reverse_relationships

 	  has_many :slams

	  before_save { |user| user.email = email.downcase }
  	  before_save :create_remember_token

	  validates :name, presence: true, length: { maximum: 50 }
	  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	  validates :email, presence:   true,
	                    format:     { with: VALID_EMAIL_REGEX },
	                    uniqueness: { case_sensitive: false }
	  validates :password, presence: true, length: { minimum: 6 }
	  validates :password_confirmation, presence: true

	  #default_scope order: 'microposts.created_at DESC'

		def feed
    		# This is preliminary. See "Following users" for the full implementation.
    		#Micropost.where("user_id = ?", id)
    		    Micropost.from_users_followed_by(self)

  		end

  		 def following?(other_user)
		    relationships.find_by_followed_id(other_user.id)
		 end

		 def follow!(other_user)
		    relationships.create!(followed_id: other_user.id)
		 end

		 def unfollow!(other_user)
		    relationships.find_by_followed_id(other_user.id).destroy
		 end

  		
  		
	  private

    	def create_remember_token
      		self.remember_token = SecureRandom.urlsafe_base64
    	end

	  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_filter :signed_in_user, only: [:index, :edit, :update, :destroy, :maps, :following, :followers ]
before_filter :correct_user,   only: [:edit, :update]
before_filter :admin_user,     only: :destroy

  def maps

    @user = User.all 

    @user.each do |u|
        puts "#{u.latitude}"
    end

  end

  def following

    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'

  end

  def followers

     @title = "Followers"
     @user = User.find(params[:id])
     @users = @user.followers.paginate(page: params[:page])
     render 'show_follow'
  
  end

  def new

  	@user = User.new
  	
  end

  def show

	 @user = User.find(params[:id])
   @microposts = @user.microposts.all

  end

  def create

    @user = User.new(params[:user])

    
      if @user.save

        UserMailer.welcome_email(@user).deliver
        #respond_to do |format|
            # format.html { render :template => "users/confirmation" }
        #end
       # format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        sign_in @user
        flash[:success] = "Welcome to the Sample App!"
        redirect_to @user
      else
        #format.html { render :action => "new" }
        render 'new'
      end
    
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def index

      @user = User.all 
      
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      # Handle a successful update.
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

   private

   # def signed_in_user
    #  unless signed_in?
     #   store_location
      #  redirect_to signin_url, notice: "Please sign in."
      #end
    #end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user)
	    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
	    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  	end
  	
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/confirmation.html.erb
<html>
<h4>Please check your mail to get the credentials</h4>
</html>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object%>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<head>
  <title>
</title>
<h1>All users</h1>
</head>
<ul class="users">
  <% @user.each do |user| %>
   <%= render user %>
  <% end %>
</ul>

app/views/users/maps.html.erb
<% provide(:title,"Maps") %>

<html>
<head>
<script
src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false">
</script>

<script>
var locations = new Array();
	
	<% @user.each do |user| %>
	locations.push(['<%= user.name %>',<%= user.latitude %>, <%= user.longitude %>]);
	<% end %>
function initialize()
{
	var center = new google.maps.LatLng(51.508742,-0.120850);
	if (navigator.geolocation)
    {
	    navigator.geolocation.getCurrentPosition(function(position){
	    	console.log(position.coords.latitude);
	    	center = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
	    	showMarkers(center);
	    });
    }
    else
    	showMarkers(center);
    console.log(center);


}

function showMarkers(center){
	var mapProp = {
	  center:center,
	  zoom:5,
	  mapTypeId:google.maps.MapTypeId.ROADMAP
	};
	var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
	console.log(mapProp.center);
	var marker ,i;
	 var infowindow = new google.maps.InfoWindow();
	for (i = 0; i < locations.length; i++) {  
	      marker = new google.maps.Marker({
	        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
	        map: map
	      });
	google.maps.event.addListener(marker, 'click', (function(marker, i) {
	        return function() {
	          infowindow.setContent(locations[i][0]);
	          infowindow.open(map, marker);
	        }
	      })(marker, i));
	}
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>
</head>

<body>
<div id="googleMap" style="width:700px;height:480px;"></div>


</body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>


      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :location, "Location" %>
      <%= f.text_field :location %>

      <%= f.label :latitude %>
      <%= f.text_field :latitude %>

      <%= f.label :longitude %>
      <%= f.text_field :longitude %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>

      <button onclick="getLocation()">Get my Location</button> <br/><br/>

  </div>
</div>

<script>
function getLocation()
  {
  if (navigator.geolocation)
    {
    navigator.geolocation.getCurrentPosition(showPosition);
    }
  else{x.innerHTML="Geolocation is not supported by this browser.";}
  }
function showPosition(position)
  {
    document.getElementById("user_latitude").value = position.coords.latitude;
    document.getElementById("user_longitude").value = position.coords.longitude;
  }
</script>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    
  </aside>
   <div class="span8">
    <%= render 'follow_form' if signed_in? %>
    
    <%= button_to "Slam book",  slams_new_path(:id=>@user.id) %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>